### ISSUE TITLE
Make accessible as trait

### ISSUE THREAD

**Issue by capocasa** [TCB13/SubStringy#1]
Thanks for making SubStringy!!!

For my project, I will be converting SubStringy to a trait and using it in my own Stringy class.

I suggest you do the same, and keep a SubStringy class around that implements that trait to have the best of both worlds.

I could just use SubStringy but that would conflict with other Stringy extensions.

This would be the rudiment of a Stringy extension econsystem, and you'd be first ;)

**Comment by TCB13** [comment]
Hi @carlocapocasa thanks for the feedback. I actually was thinking about this some time ago, but never implemented. Can you do a PR with the code converted to a trait? I would be glad to accept it! Don't forget to fix the unit tests! ;)

**Comment by TCB13** [comment]
@carlocapocasa feature available since d71aafa.
