### ISSUE TITLE
Publish the library on Packagist

### ISSUE THREAD

**Issue by ker0x** [TCB13/SubStringy#5]
I suggest you to publish your library on [Packagist](https://packagist.org/), so people no longer need to add your github repository in their `composer.json` to require it!

They will just need to do `composer require tcb13/substringy`

**Comment by TCB13** [comment]
Done! 🥇 I'll update the documentation very soon.

**Comment by TCB13** [comment]
Closed by cc31d30a17eab702cc1588c19b905efe97227e39.
